pipeline {
    agent any

    environment {
        IMAGE_NAME = "demishuaccha/frontend-service"
        IMAGE_TAG  = "latest"
        DOCKER_CREDENTIAL_ID = 'dockerhub-creds'
        // Este nombre debe coincidir exactamente con tu carpeta en Git
        FRONT_DIR = "microservice-front" 
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Login to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: env.DOCKER_CREDENTIAL_ID, usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                        bat "docker login -u %USER% -p %PASS%"
                    }
                }
            }
        }

        stage('Build Frontend') {
            steps {
                // Entramos a la carpeta para instalar y compilar
                dir("${env.FRONT_DIR}") {
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    // Construimos la imagen usando la carpeta como contexto
                    bat "docker build -t ${env.IMAGE_NAME}:${env.IMAGE_TAG} ./${env.FRONT_DIR}"
                    bat "docker push ${env.IMAGE_NAME}:${env.IMAGE_TAG}"
                }
            }
        }

        stage('Deploy to Minikube') {
            steps {
                script {
                    // Entramos a microservice-front donde está la carpeta k8s
                    dir("${env.FRONT_DIR}") {
                        echo "--- Aplicando TODA la configuración de k8s ---"
                        // Al usar -f k8s/ aplicamos los 3 archivos de la imagen automáticamente
                        bat "kubectl apply -f k8s/"
                    }
                    
                    echo "--- Esperando que los Pods estén listos ---"
                    // Nota: Asegúrate que el label 'app' en keycloak-service.yml sea 'keycloak'
                    bat "kubectl wait --for=condition=ready pod -l app=keycloak --timeout=180s"
                    bat "kubectl wait --for=condition=ready pod -l app=frontend-service --timeout=120s"
                }
            }
        }
    }

    post {
        success {
            echo "¡Despliegue exitoso!"
            script { bat "docker logout" }
        }
        failure {
            echo "Fallo en el pipeline. Revisa que los nombres de los archivos .yml sean correctos."
        }
    }
}